# Generated by Django 4.2.15 on 2024-09-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentCourse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
